In [12]:
import numpy as np
import matplotlib.pyplot as plt

def pcaWeights(cov, riskDist=None, riskTarget=1.0, normalize=True):
    """
    PCAを用いてリスク配分に基づくポートフォリオの重みベクトルを計算する。
    
    Parameters:
    cov (numpy.ndarray): 資産リターンの共分散行列。
    riskDist (numpy.ndarray or None): リスク配分を示すベクトル。指定がない場合は、最後のリスク要素にリスクを集中。
    riskTarget (float): ポートフォリオ全体のリスク目標値。デフォルトは1.0。
    
    Returns:
    numpy.ndarray: 計算された重みベクトル。
    """
    # 共分散行列の固有値と固有ベクトルを計算
    eVal, eVec = np.linalg.eigh(cov)
    
    # 固有値を大きい順にソート
    indices = eVal.argsort()[::-1]
    eVal, eVec = eVal[indices], eVec[:, indices]
    print(eVal)
    print(eVec)
    
    # リスク配分が指定されていない場合、最後のリスク要素にリスクを集中
    if riskDist is None:
        riskDist = np.zeros(cov.shape[0])
        riskDist[-1] = 1.0  # 最後のリスク要素に1を設定
    
    # リスク要素ごとの負荷を計算
    loads = riskTarget * (riskDist / eVal)**0.5
    print(loads)
    
    # 重みベクトルを計算
    wgths = np.dot(eVec, np.reshape(loads, (-1, 1)))

    #総和が1になるように正規化
    if normalize:
        wgths /= np.sum(wgths)
    
    # 必要であれば、リスク分布の確認を行う（コメントアウトを解除して使用可能）
    # ctr = (loads / riskTarget)**2 * eVal  # リスク分布の確認
    # print(ctr)  # 確認用に出力
    
    return wgths


# 3つの資産の共分散行列を定義
cov_matrix = np.array([[1, 0.02, 0.04],
                       [0.02, 1, 0.03],
                       [0.04, 0.03, 1]])

riskdist = np.array([0.3, 0.2, 0.5])

# PCAを用いて重みベクトルを計算
weights = pcaWeights(cov_matrix, riskDist=riskdist)

# 計算された重みを表示
print("Calculated Weights:\n", weights)
print(np.sum(weights))


[1.06074674 0.98113209 0.95812117]
[[-0.58437383  0.54492509 -0.60130182]
 [-0.50578521 -0.82403773 -0.25523155]
 [-0.63457746  0.15497893  0.75716113]]
[0.53180789 0.45149325 0.72239509]
Calculated Weights:
 [[ 0.47760137]
 [ 0.78981688]
 [-0.26741825]]
1.0000000000000002
