In [5]:
import numpy as np
np.linspace(0, 10, 11)[1:-1]

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
a = np.random.randint(0, 10, 10)
print(a)

[3 9 5 6 4 7 4 4 1 9]


In [15]:
def print_array(a):
    b, c, d = a
    return b, c, d
print(print_array([1, 2, 3]))

(1, 2, 3)


In [20]:
num_dizitized = 2
digitized = [1, 2, 3]
sum([x * (num_dizitized**i) for i, x in enumerate(digitized)])


17

In [23]:
import gym
env = gym.make('CartPole-v1', render_mode='rgb_array')

state, info = env.reset()
print(state)
print(info)

[-0.04654604 -0.03725863 -0.0054361  -0.0017145 ]
{}


In [25]:
import gym
env = gym.make('CartPole-v0')
observation = env.reset()
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info, _ = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

(array([-0.00081611, -0.04655476,  0.02890223,  0.04915942], dtype=float32), {})
[-0.00174721  0.1481411   0.02988542 -0.23426631]
[ 0.00121562  0.3428236   0.0252001  -0.51737463]
[ 0.00807209  0.14735603  0.0148526  -0.21685837]
[ 0.01101921  0.34226254  0.01051543 -0.5048194 ]
[ 0.01786446  0.146994    0.00041905 -0.20884128]
[ 0.02080434  0.34210995 -0.00375778 -0.501392  ]
[ 0.02764654  0.14704117 -0.01378562 -0.20989567]
[ 0.03058736 -0.04788098 -0.01798353  0.07840694]
[ 0.02962974 -0.24274057 -0.01641539  0.3653622 ]
[ 0.02477493 -0.43762544 -0.00910815  0.6528242 ]
[ 0.01602242 -0.24237785  0.00394834  0.3572872 ]
[ 0.01117487 -0.04731225  0.01109408  0.06585189]
[ 0.01022862 -0.24259149  0.01241112  0.36201432]
[ 0.00537679 -0.04764812  0.0196514   0.07327057]
[ 0.00442383  0.14718667  0.02111682 -0.21314806]
[ 0.00736756  0.34200045  0.01685385 -0.49909568]
[ 0.01420757  0.5368808   0.00687194 -0.78641987]
[ 0.02494519  0.73190767 -0.00885646 -1.0769329 ]
[ 0.03958334  0.536

/home/shimizu/reinforce/venv/lib/python3.9/site-packages/gym/envs/registration.py:555: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.warn(
/home/shimizu/reinforce/venv/lib/python3.9/site-packages/gym/envs/classic_control/cartpole.py:211: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("CartPole-v0", render_mode="rgb_array")
  gym.logger.warn(
/home/shimizu/reinforce/venv/lib/python3.9/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):
